import React, { useState, useEffect } from 'react';
import { Layout } from '../components/Layout';
import { Button } from '../components/ui/Button';
import { getTodaySales, closeDay } from '../services/api';
import { Sale } from '../types';
import { Lock, AlertTriangle, CheckCircle } from 'lucide-react';

export const Closing: React.FC = () => {
  const [sales, setSales] = useState<Sale[]>([]);
  const [loading, setLoading] = useState(false);
  const [closed, setClosed] = useState(false);

  useEffect(() => {
    load();
  }, []);

  const load = async () => {
    try {
      const data = await getTodaySales();
      setSales(data);
    } catch (error) {
      console.error("Failed to load today's sales", error);
    }
  };

  const calculateTotals = () => {
    const methods = { total: 0, cash: 0, pix: 0, debit: 0, credit: 0 };
    sales.forEach(s => {
        methods.total += s.total_amount;
        // Helper to add to specific bucket
        const add = (m: string, v: number) => {
            if (m === 'DINHEIRO') methods.cash += v;
            if (m === 'PIX') methods.pix += v;
            if (m === 'DEBITO') methods.debit += v;
            if (m === 'CREDITO') methods.credit += v;
        };
        add(s.payment_method_1, s.payment_value_1);
        if (s.payment_method_2 && s.payment_value_2) add(s.payment_method_2, s.payment_value_2);
    });
    return methods;
  };

  const totals = calculateTotals();

  const handleClose = async () => {
    if (!window.confirm("Confirma o fechamento do caixa? Esta ação não pode ser desfeita.")) return;
    
    setLoading(true);
    try {
        await closeDay({
            id: '', // Generated by DB
            created_at: '', // Generated by DB
            date: new Date().toISOString().split('T')[0],
            total_amount: totals.total,
            total_cash: totals.cash,
            total_pix: totals.pix,
            total_debit: totals.debit,
            total_credit: totals.credit,
            sale_count: sales.length
        });
        setClosed(true);
    } catch (e: any) {
        alert("Erro: " + e.message);
    } finally {
        setLoading(false);
    }
  };

  if (closed) {
    return (
        <Layout>
            <div className="flex flex-col items-center justify-center min-h-[60vh] text-center space-y-4">
                <CheckCircle className="w-24 h-24 text-green-500" />
                <h2 className="text-2xl font-bold dark:text-white">Caixa Fechado!</h2>
                <p className="text-gray-500">O movimento de hoje foi salvo no histórico com segurança.</p>
            </div>
        </Layout>
    )
  }

  return (
    <Layout>
      <div className="space-y-6">
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-900/50 p-4 rounded-xl flex gap-3">
           <AlertTriangle className="text-red-500 w-6 h-6 flex-shrink-0" />
           <p className="text-sm text-red-800 dark:text-red-200">
             Atenção: Ao fechar o caixa, você não poderá mais editar ou adicionar vendas para a data de hoje.
           </p>
        </div>

        <div className="bg-white dark:bg-gray-900 p-6 rounded-2xl shadow-sm space-y-4">
            <h2 className="text-center text-gray-500 text-sm uppercase tracking-widest">Total Geral</h2>
            <p className="text-center text-5xl font-bold text-gray-900 dark:text-white">R$ {totals.total.toFixed(2)}</p>
            
            <div className="grid grid-cols-2 gap-4 pt-4 border-t border-gray-100 dark:border-gray-800">
                <div className="text-center">
                    <p className="text-xs text-gray-400">Dinheiro</p>
                    <p className="font-semibold dark:text-gray-200">R$ {totals.cash.toFixed(2)}</p>
                </div>
                <div className="text-center">
                    <p className="text-xs text-gray-400">Pix</p>
                    <p className="font-semibold dark:text-gray-200">R$ {totals.pix.toFixed(2)}</p>
                </div>
                <div className="text-center">
                    <p className="text-xs text-gray-400">Débito</p>
                    <p className="font-semibold dark:text-gray-200">R$ {totals.debit.toFixed(2)}</p>
                </div>
                <div className="text-center">
                    <p className="text-xs text-gray-400">Crédito</p>
                    <p className="font-semibold dark:text-gray-200">R$ {totals.credit.toFixed(2)}</p>
                </div>
            </div>
        </div>

        <Button 
            fullWidth 
            variant="primary" 
            className="!bg-gray-900 !text-white dark:!bg-white dark:!text-black py-4 mt-8"
            onClick={handleClose}
            disabled={loading || sales.length === 0}
        >
            <Lock className="w-5 h-5 mr-2" />
            {loading ? 'Fechando...' : 'Encerrar Caixa Agora'}
        </Button>
      </div>
    </Layout>
  );
};
